### ISSUE TITLE
Android project not building - VS2017

### ISSUE THREAD

**Issue by dansiegel** [dansiegel/Prism-Templates#12]
A generated solution will build just fine in VS4Mac but when building the Android project in VS2017 there are several build errors pointing at Android Support Libraries not being referenced properly.

**Comment by stuartparkinsonuk** [comment]
I have hit this and stopped dead - do you know of a manual workaround while this is getting looked at?

It will generate and build and run a 'non-data' sample solution just fine, but add AzureMobileServices AADB2C and it won't build - complains (a lot) about 'cannot find symbol...' which I guess is what you're seeing.

I'm hoping that a simple fix to the project files or removing/adding nugets would fix it, but I've not been able to get anywhere and my knowledge of the Xamarin system is limited.

EDIT actually seems to be a problem with AzureMobileClient.Helpers. If I create a plain vanilla Xamarin app and upgrade to netstandard it builds and runs fine. Add the AzureMobileClient.Helpers nuget and it will no longer build - cannot find symbols for  android.suppor.customtabs...

**Comment by dansiegel** [comment]
Sorry for not updating this issue... the issue was actually fixed a while ago.
