### ISSUE TITLE
IsActiveChanged null in ViewModel base

### ISSUE THREAD

**Issue by lhughey** [dansiegel/Prism-Templates#13]
Thanks for creating these templates.  They are a real time saver and really simplify prism Tabbed navigation.  

The ViewModelBase class doesn't contain instantiate the IsActiveChanged eventHandler resulting in an exception when trying to use any page that implements IActiveAware. 

If anyone should run into this issue before its fixed,  it is easily fixed by adding the following line to the constructor.

` IsActiveChanged += (sender, e) => System.Diagnostics.Debug.WriteLine($"{Title} IsActive: {IsActive}");`

Thanks.

**Comment by dansiegel** [comment]
Glad that this is helping you out. There is no reason for the ViewModelBase to attach any event handler. [PropertyChanged.Fody](/Fody/PropertyChanged) handles event changes with the private method `OnIsActiveChanged`. When IsActive is changed it will Raise IsActiveChanged if anything is attached... but it also provides you two virtual methods to use `OnIsActive` & `OnIsNotActive` thus allowing you to split your logic up based on the state of IsActive.
