### ISSUE TITLE
using Android.App is missing on top of AndroidInitializer.cs

### ISSUE THREAD

**Issue by pedramp20** [dansiegel/Prism-Templates#16]
When a project using the following command is created on Windows.

`dotnet new prismforms -id com.company.app -fr netstandard1.6 -localization -mc -ios-secret "xxxx-xxxx-xxxx-xxxxxxxx" -android-secret "xxx-xxxxxx-xxxxxx-xxxxxxx" -data None -au AADB2C -client-id "xxxx-xxxx-xxxxx-xxxxxxx" -di Unity`

`AndroidInitializer.cs` is missing a reference to `Android.App` and as the result `Activity` symbol in the following code cannot be resolved.

`container.RegisterInstance(new UIParent(Xamarin.Forms.Forms.Context as Activity));`

**Comment by dansiegel** [comment]
This among several other issues has been resolved and will be available in 1.0.9 available shortly
