### ISSUE TITLE
Projects wont load due to Directory.build.targets tag not closed

### ISSUE THREAD

**Issue by lhughey** [dansiegel/Prism-Templates#19]
The tag in line 18 in the solution's directory.build.targets is not closed, which causes the solution's projects not to load.  The fix is close the tag as mentioned in  [response 5](https://github.com/dansiegel/Prism-Templates/issues/14#issuecomment-333751583)

**Comment by dansiegel** [comment]
Line 18 is blank... I believe you have an older version installed. Please run `dotnet new -i Prism.Forms.QuickstartTemplates::*`

**Comment by lhughey** [comment]
Thanks.  I previously ran the command a few hours ago.  There must have been a glitch in my matrix because there was no output from the command.  

`PS C:\Source\Summation.Mobile> dotnet new -i "Prism.Forms.QuickstartTemplates::*"`
`PS C:\Source\Summation.Mobile> dotnet new prismforms -id "com.summation.mobile" -n "Summation.Mobile"`

I ran it again and it took.  I now know to expect textual confirmation with Net Core new commands.   Thanks

**Comment by dansiegel** [comment]
Not a problem... keep in mind the latest updates will exclude both your Info.plist and AndroidManifest.xml from SCM, there is version in the build directory that will copy to the correct location if the file is missing. You can tokenize any sensitive Client Ids in those templates for your Build Server.
