### ISSUE TITLE
How to use template

### ISSUE THREAD

**Issue by Im-PJ** [dansiegel/Prism-Templates#2]
Is there a nuget package or is it VS extension?
How to use these templates?

**Comment by dansiegel** [comment]
keep in mind these are still beta so some features things may not work quite right. I do have a [myget feed](https://www.myget.org/F/dansiegel-templates/) as well that you can install from. But the easiest right now is probably just to clone the repo and install the templates.

Right now the templates are all CLI based, the VS teams are working to get integration in VS2017 and VS4Mac. I'll add some how to info to the ReadMe later today.

**Comment by dansiegel** [comment]
I've updated the ReadMe with all of the information you should need. If you need additional help let me know.
