### ISSUE TITLE
I am unable to include UWP

### ISSUE THREAD

**Issue by chrisgate** [dansiegel/Prism-Templates#20]
this is what i am using 
dotnet new prismforms -id com.dinkkiia.workandplay -n Dinkkiia.Workandplay  --include-uwp true -fr netstandard2.0 -di unity -data AzureMobileClient -barcode true

**Comment by dansiegel** [comment]
Thanks for reminding me about this... currently the template only supports UWP when targeting netstandard1.4... I need to update the template to target the Fall Creators Update so I can add support for netstandard2.0... I'm working on a few other changes to the templates and should have that support in the next day or so. In the mean time target 1.4, I would suggest simply updating Dinkkiia.Workandplay.csproj to target 2.0 and change `PackageTargetFallback` to `AssetTargetFallback`, you'll also need to update the targets for the UWP project.

**Comment by chrisgate** [comment]
Thanks....I will do as you said but i will also be waiting for the update i reminded you of...thanks in anticipations

**Comment by chrisgate** [comment]
Everything work fine but i go this error on UWP
Can't load types from xmlns http://schemas.microsoft.com/winfx/2006/xaml/presentation	Dinkkiia.Workandplay.UWP	C:\test\Dinkkiia.Workandplay\src\Dinkkiia.Workandplay.UWP\App.xaml

I am unable to resolve it from googling.

Thanks

**Comment by dansiegel** [comment]
are you sure that you have the tooling installed for UWP Development? Remember you will need Visual Studio 2017 with the `Universal Windows Platform development` Workload installed. Simply installing the `Mobile development with .NET` (aka Xamarin) Workload is not enough to allow you to do UWP.

**Comment by chrisgate** [comment]
I have the workload sir....i can use netstandard2.0 without the template sir

**Comment by chrisgate** [comment]
I just noticed its only happened on prismforms

**Comment by dansiegel** [comment]
please let me know if the latest template fixes your issue.

**Comment by chrisgate** [comment]
Thanks Dan for your time...........the latest template doesnt build in all framework at all

Can you create prismforms project and try to build..


Cheers

**Comment by chrisgate** [comment]
i always have this error ..................is it from me?


Severity	Code	Description	Project	File	Line	Suppression State
Error		System.IO.FileNotFoundException: Could not load file or assembly 'System.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Mobile.BuildTools.Generators.SecretsClassGenerator.Execute()
   at Mobile.BuildTools.Tools.SecretsJsonTask.Execute()

=== Pre-bind state information ===
LOG: DisplayName = System.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
 (Fully-specified)
LOG: Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/MSBuild/15.0/Bin/
LOG: Initial PrivatePath = NULL
Calling assembly : Mobile.BuildTools, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null.
===
LOG: This bind starts in LoadFrom load context.
WRN: Native image will not be probed in LoadFrom context. Native image will only be probed in default load context, like with Assembly.Load().
LOG: Using application configuration file: C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\15.0\Bin\MSBuild.exe.Config
LOG: Using host configuration file: 
LOG: Using machine configuration file from C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
LOG: Post-policy reference: System.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
LOG: The same bind was seen before, and was failed with hr = 0x80070002.
	Dinkkiia.CloudUtilities	C:\Users\Chrisgate\.nuget\packages\mobile.buildtools\1.0.2\build\Mobile.BuildTools.targets	52	

Thanks

**Comment by dansiegel** [comment]
no it's not from you, that's a bug in the Mobile.BuildTools that should only exist in a pre-release... can you please open an [issue for that in that repo](/dansiegel/Mobile.BuildTools/issues/new)

**Comment by chrisgate** [comment]
I hope it will be fix fast because boss on me to start a project and i want to use the awesome template to jumpstart easily.

Thanks and Cheers

**Comment by chrisgate** [comment]
Dan, with  Mobile.BuildTools" Version="1.0.5" .....i am still getting below error in all the platforms. Is it my machine?

Error		Specified cast is not valid.


Thanks for your Time.

Cheers.

Happy new week.

**Comment by dansiegel** [comment]
@chrisgate try obliterating your obj/bin folders. If that doesn't work try purging Mobile.BuildTools from your local NuGet cache. I also suggest keeping VS closed when you do that, so it will try to restore everything on Project load.

**Comment by chrisgate** [comment]
@dansiegel thanks for your time,

I am unable to get any from of the template to work even with what you suggested.

Every Xamarin projects/solutions work okay.

I dont know what's happening anymore .

Thanks for your help once again!!!

Chris

**Comment by dansiegel** [comment]
the only other suggestion I would have with the issue you were having with Mobile.BuildTools is to back down to 1.0.0 as it uses PowerShell you may have better luck with that. Unfortunately I cannot publish an update to the templates until we release the next preview for Prism as there were breaking changes for the Popups Plugin in the last Preview and major breaking changes merged last night.

**Comment by chrisgate** [comment]
Thanks @dansiegel

**Comment by chrisgate** [comment]
@dansiegel any update coming?

**Comment by dansiegel** [comment]
Yes working on some updates for the Popup plugin and BuildTools before I release an update to the Templates.

**Comment by chrisgate** [comment]
Thanks @dansiegel i will be here every step of it......cheers

**Comment by chrisgate** [comment]
Happy Holiday @dansiegel  and Happy new Year in advance.....I hope we can have the much awaiting update in early January.

God bless you and more success in 2018.

Cheers !!!

Chris

**Comment by Orgbrat** [comment]
@dansiegel  I am trying to create my first Prism 7.0 SR1 solution using the Prism Quickstart Templates.
But with Mobile.BuildTools" Version="1.0.5" .....I am getting the below error in all the platforms as other folks are... I have followed all your suggestions above, deleting bin and obj folders and clearing Nuget cache but errors still there. Is there someway to fix this?

Error Specified cast is not valid.

Thanks for your Time.

Orgbrat

**Comment by chrisgate** [comment]
@Orgbrat use Mobile.BuildTools" Version="1.0.0" and delete bin and obj folders and clear Nuget cache.

@dansiegel is working on the Mobile.BuildTools for us.

**Comment by dansiegel** [comment]
@chrisgate @Orgbrat you can track the issue with the BuildTools at dansiegel/Mobile.BuildTools#6. I am closing this issue as it seems that this is the only real issue and UWP should be fine now.

**Comment by chrisgate** [comment]
thanks

**Comment by Orgbrat** [comment]
@dansiegel  Thanks...

**Comment by chrisgate** [comment]
Cast is gone but i am still having this

Severity	Code	Description	Project	File	Line	Suppression State
Error		Can't load types from xmlns http://schemas.microsoft.com/winfx/2006/xaml/presentation	Dink.SmartTags.UWP	C:\chrisgate\Dink.SmartTags\src\Dink.SmartTags.UWP\App.xaml		

then

            global::FFImageLoading.Forms.Droid.CachedImageRenderer.Init(); error  in the MainActivity
i guess is asking for true or false as argument 


Thanks @dansiegel

**Comment by dansiegel** [comment]
Your issue with Droid has already been fixed. You'll need to update that like shown here:

```cs
global::FFImageLoading.Forms.Droid.CachedImageRenderer.Init(enableFastRenderer: true);
```

As for the other issue I'll have to take a look to see if I can reproduce it

**Comment by Orgbrat** [comment]
FYI, I am also getting the error on UWP project
Can't load types from xmlns http://schemas.microsoft.com/winfx/2006/xaml/presentation 

Update us if you can.  Your efforts are very much appreciated :)

Thanks Dan...

**Comment by chrisgate** [comment]
i dont think that UWP error is from Mobile build......as at Oct 2017 every thing work perfect bcoz i created multiple playing apps with it.


Thanks

**Comment by chrisgate** [comment]
@dansiegel I really wish i can be doing what u r doing now.....God bless u more.

I saw the new issue u opened!

For template like this i dont know how u are doing it but if u can re-upload or update all the projects most part will be solved.

Why i think so is,there is no minor or major release or update u made since i have found this template that i haven't tested  and what i found out was since Standard 2.0 came along, I for one always have errors here and there.

And i believe if u can re-upload the working template u have on your machine,all will be well.

Thanks
