### ISSUE TITLE
Create VSIX for VS 2017 integration

### ISSUE THREAD

**Issue by dansiegel** [dansiegel/Prism-Templates#23]
A Custom UI and VSIX will need to be generated to integrate the templates into Visual Studio 2017

**Comment by dansiegel** [comment]
New projects fail to create. The Output in VS during debug shows an error about `Cannot get 'Author'`. Installing the generated VSIX directly results in a generated solution with an error that it cannot create `{ProjectName}.csproj` because it already exists.

```
System.Windows.Data Warning: 40 : BindingExpression path error: 'Extension' property not found on 'object' ''VsTemplate' (HashCode=-882052724)'. BindingExpression:Path=Extension; DataItem='VsTemplate' (HashCode=-882052724); target element is 'StackPanel' (Name=''); target property is 'Visibility' (type 'Visibility')
System.Windows.Data Error: 17 : Cannot get 'Author' value (type 'String') from '' (type 'VsTemplate'). BindingExpression:Path=Author; DataItem='VsTemplate' (HashCode=-882052724); target element is 'AutomationTextBlock' (Name=''); target property is 'Name' (type 'String') TargetInvocationException:'System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotImplementedException: The method or operation is not implemented.
   at Microsoft.VisualStudio.TemplateProviders.Implementation.VsTemplate.get_Author()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.GetValue(Object obj, Object[] index)
   at MS.Internal.Data.PropertyPathWorker.GetValue(Object item, Int32 level)
   at MS.Internal.Data.PropertyPathWorker.RawValue(Int32 k)'
```

@mlorbetske @seancpeters any ideas what could be causing this? The code is in the vs2017 branch

**Comment by seancpeters** [comment]
+ Phil

**Comment by phenning** [comment]
At first glance. this doesn't look specific to the new dotnet template engine integration in Visual Studio, instead it looks like an issue with the .vstemplate authoring. If you can provide a pointer to it, I can try to help out.

**Comment by dansiegel** [comment]
@phenning the templates themselves work just fine in the dotnet cli & in the VS Mac Addin... I'm just having some trouble with VS integration here... you can see it all [here](https://github.com/dansiegel/Prism-Templates/tree/vs2017/TemplatePack)

**Comment by phenning** [comment]
Thanks, I'll install Xamarin this afternoon and see if I can debug what is going on. The exception above is definitely coming from the old VS Template engine though (from the stack above: **Microsoft.VisualStudio.TemplateProviders.Implementation**)

For more information, which version/build of Visual Studio were you testing on?

**Comment by dansiegel** [comment]
thanks @phenning 

Microsoft Visual Studio Professional 2017 
Version 15.5.6
VisualStudio.15.Release/15.5.6+27130.2027
Microsoft .NET Framework
Version 4.7.02558

**Comment by FrederickBrier** [comment]
This same exception is occurring in my VSiX plugin. Do you have time to explain what the original problem and solution were?

**Comment by softerj** [comment]
Same error here
