### ISSUE TITLE
Just a Question

### ISSUE THREAD

**Issue by mzhukovs** [dansiegel/Prism-Templates#25]
Can someone please point me to (either in the source code here or just a good resource online in general) how Prism adds a ViewModel along with your page template and a line of code in your App class to register it with the ioc container for navigation? That's a nice feature that I'm looking to replicate. Any help would be much appreciated.

**Comment by dansiegel** [comment]
These templates are done with the new dotnet template engine, it's all open source you're welcome to have a look... or you can see the official [Prism Extensibility](https://github.com/PrismLibrary/Prism-Extensibility) repo
