### ISSUE TITLE
I still can pull the new update.....?

### ISSUE THREAD

**Issue by chrisgate** [dansiegel/Prism-Templates#26]
I am sorry if i am been aggressive .

Hope your holidays went well.

Cheers

**Comment by dansiegel** [comment]
The updated templates are now available... I've got the build process updated so I can release updates a lot easier now.

**Comment by chrisgate** [comment]
@dansiegel Do you know why i am getting this error 

Error		Specified cast is not valid.

Throughout today i have been trying to get the new template for work


Thanks in anticipations

Chris.

**Comment by dansiegel** [comment]
what is the command you used to create the template?

**Comment by chrisgate** [comment]
@dansiegel  i used 

 dotnet new prismforms -id com.dink.smarttags -n Dink.SmartTags --include-uwp true  -data AzureMobileClient -barcode true -acr
 true

Thanks

**Comment by chrisgate** [comment]
Also this Error
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0433	The type 'Color' exists in both 'Splat, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null' and 'netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'

**Comment by dansiegel** [comment]
ok, I'll take a look at this as soon as I get a chance... probably won't be until tomorrow or Friday though

**Comment by chrisgate** [comment]
@dansiegel  i will remind u later today........i guess the issues was partly from Mobile.BuildTools.


thanks

**Comment by chrisgate** [comment]
C:\Users\Chrisgate\.nuget\packages\mobile.buildtools\1.0.5\build\Mobile.BuildTools.targets(41,5): error : Specified cast is not valid.

**Comment by chrisgate** [comment]
soft reminder!!!

**Comment by dansiegel** [comment]
@chrisgate it seems you're hitting two different issues here

For the Mobile.BuildTools this is a known issue I'm looking into
For the Splat issue that is out of my control. You can track it here: reactiveui/splat#152

If you update to Acr.UserDialogs v7 it removes the dependency on Splat, unfortunately because you're also using the AzureMobileClient.Helpers which is using Akavache which uses Splat... you're still stuck with the Splat issue.

**Comment by chrisgate** [comment]
Thanks @dansiegel the Acr.UserDialogs v7 did it for Splat and i ahve removed AzureMobileClient.Helpers .

for Mobile.BuildTools, which version should use bcoz i am using 1.0.0 from earlier suggestion but i still cant get it to build and i know u r using one now,please which version can i use. I am on window 10 PC


Thanks for ur work.

cheers

**Comment by dansiegel** [comment]
V1.0.0 should work... you may need to do a clean and nuke your obj/bin folders
