### ISSUE TITLE
New view files are named itemtemplate.xaml instead of class name

### ISSUE THREAD

**Issue by lhughey** [dansiegel/Prism-Templates#28]
New views are are named "ItemTemplate.xaml" instead of the class name when creating new items using 
`dotnet new prismitem -n "GeneralPopupPage" -namespace $namespace`

All of the code within the view is correct. 

This is using the latest version of the templates, as I pulled a new version this morning.

**Comment by dansiegel** [comment]
can you please provide the output from `dotnet --info`.

**Comment by lhughey** [comment]
Sure

`.NET Command Line Tools (2.1.4)

Product Information:
 Version:            2.1.4
 Commit SHA-1 hash:  5e8add2190

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.16299
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.1.4\

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.5
  Build    : 17373eb129b3b05aa18ece963f8795d65ef8ea54`

**Comment by dansiegel** [comment]
It seems you have uncovered a bug in the dotnet template engine... there is currently a PR to fix the issue and it will be available in a future release. There is ultimately nothing I can do on my end to fix this. You can track the issue further in the dotnet templating issue referenced above.

**Comment by lhughey** [comment]
Thanks for looking into this and for all the work you do with prism.

**Comment by dansiegel** [comment]
@lhughey you can try a nightly build of the dotnet template engine (dotnet new) in the next day or two as the fix for this was merged earlier today.

**Comment by lhughey** [comment]
Thanks for the update @dansiegel
