### ISSUE TITLE
Fix UWP Platform Project

### ISSUE THREAD

**Issue by dansiegel** [dansiegel/Prism-Templates#29]
# Description

As reported in #20 upon building there is a build error:

```
Error:	Can't load types from xmlns http://schemas.microsoft.com/winfx/2006/xaml/presentation
```

The UWP project will need to be updated and fixed

**Comment by dansiegel** [comment]
this is now fixed and will be available in the next release

**Comment by chrisgate** [comment]
I am in my happy mode now............God bless u more.........Thanks @dansiegel

**Comment by chrisgate** [comment]
@dansiegel I am still having this error in 1,4

**Comment by dansiegel** [comment]
@chrisgate you might try creating a UWP project and manually adding it. I've updated the template based on the latest from the official Xamarin Forms/NetStandard template in VS2017.

**Comment by chrisgate** [comment]
Thanks

**Comment by chrisgate** [comment]
@dansiegel prismformsempty work perfectly...............UWP and everything in prismformsempty.

But the glory of prismforms quick start is so cool.

**Comment by dansiegel** [comment]
@chrisgate can you send me a zip with the UWP projects that work and don't work... I suppose it's possible there is something that was missed

**Comment by chrisgate** [comment]
I think something is missing bcoz when i copy UWP from prismformsempty project to prismsform project there is still this error,i think the missing is not from UWP.

Can i mail it to dsiegel@avantipoint.com?

Thanks

**Comment by chrisgate** [comment]
sent to  dsiegel@avantipoint.com

**Comment by chrisgate** [comment]
Hope u got the ZIP

**Comment by chrisgate** [comment]
@dansiegel do u get my zip..................i dont want to miss out uwp on the new version update...........thanks

**Comment by dansiegel** [comment]
@chrisgate yes I did... it's on my todo list

**Comment by chrisgate** [comment]
@dansiegel as i see u are pulling new update please dont forget this...........thanks in anticipations.
