### ISSUE TITLE
Install via NuGet fails

### ISSUE THREAD

**Issue by dansiegel** [dansiegel/Prism-Templates#4]
Installing locally `dotnet new -i content/MobileApp-CSharp/` and `dotnet new content/XamarinItems/` installs either template, however installing form a packed NuGet fails.

Not sure if @mlorbetske has made the fix to be able to see install errors?

**Comment by mlorbetske** [comment]
Unfortunately not yet - there are some bits around if the markers for a project are found but are malformed, then there are diagnostics, but if the markers aren't found then there's currently nothing. Is there a public NuPkg to try it out with or should I clone the repo to see what's happening?

**Comment by dansiegel** [comment]
I just relisted the [package](https://www.nuget.org/packages/Prism.Forms.QuickstartTemplates/1.0.0-alpha1), if you have any trouble then you may want to clone the repo...

**Comment by mlorbetske** [comment]
I see these entries

```
Prism Forms Item Templates                prismitem         [C#]              Prism/Xamarin Forms
Prism Forms Mobile App - Quickstart      prismformsqs      [C#]              Xamarin/Prism
```

after doing

```
dotnet new -i Prism.Forms.QuickstartTemplates::1.0.0-*
```

should there be more?

**Edit:** Since the package has a prerelease indicator, the `-*` is required so that NuGet restores it - maybe that's what was happening?

**Comment by dansiegel** [comment]
no it wasn't working for me... must be something wrong on my machine
